export const PERMISSIONS = {
  // Users
  USERS_CREATE: 'users.create',
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',

  // Roles & Permissions
  ROLES_MANAGE: 'roles.manage',

  // Audit Logs
  AUDIT_READ: 'audit.read',

  // System Preferences & i18n
  I18N_MANAGE: 'i18n.manage',
  PREFERENCES_UPDATE: 'preferences.update',

  // Courses & Syllabus
  COURSES_CREATE: 'courses.create',
  COURSES_READ: 'courses.read',
  COURSES_UPDATE: 'courses.update',
  COURSES_DELETE: 'courses.delete',

  // Question Bank
  QUESTIONS_CREATE: 'questions.create',
  QUESTIONS_READ: 'questions.read',
  QUESTIONS_UPDATE: 'questions.update',
  QUESTIONS_DELETE: 'questions.delete',

  // Exams
  EXAMS_CREATE: 'exams.create',
  EXAMS_READ: 'exams.read',
  EXAMS_PUBLISH: 'exams.publish',
  EXAMS_ATTEMPT: 'exams.attempt',

  // Results & Flags
  RESULTS_READ_OWN: 'results.read_own',
  RESULTS_FLAG: 'results.flag',

  // Phase 7: Published Archive
  ARCHIVE_READ: 'archive.read',
  ARCHIVE_ANSWER_KEY: 'archive.answer_key',
  ARCHIVE_CORRECT: 'archive.correct',
  ARCHIVE_EXPORT: 'archive.export',

  // Phase 8: Student Analytics & Mastery
  ANALYTICS_READ_OWN: 'analytics.read_own',
  ANALYTICS_READ: 'analytics.read',

  // Phase 9: Personalized Practice & Mastery Tracking
  PRACTICE_CREATE: 'practice.create',
  PRACTICE_READ: 'practice.read',
  PRACTICE_ATTEMPT: 'practice.attempt',
  PRACTICE_EVALUATE: 'practice.evaluate',

  // Phase 10: Preview & Impersonation System
  PREVIEW_USE: 'preview.use',
  PREVIEW_CONFIG: 'preview.config',
  IMPERSONATE_USE: 'impersonate.use',
  PREVIEW_AUDIT_READ: 'preview.audit_read',

  // Phase 11: AI Question System & Gateway
  AI_MODIFY: 'ai.modify',
  AI_GENERATE: 'ai.generate',
  AI_BATCH: 'ai.batch',
  AI_REVIEW: 'ai.review',
  AI_USAGE_READ: 'ai.usage_read',
  AI_ADMIN_CONFIG: 'ai.admin_config',

  // Phase 12: AI Interview System
  INTERVIEW_ATTEMPT: 'interview.attempt',
  INTERVIEW_READ_OWN: 'interview.read_own',
  INTERVIEW_MANAGE: 'interview.manage',
  INTERVIEW_EVALUATE: 'interview.evaluate',

  // Phase 13: Subscriptions, Entitlements & Billing
  SUBSCRIPTIONS_READ: 'subscriptions.read',
  SUBSCRIPTIONS_MANAGE: 'subscriptions.manage',
  ENTITLEMENTS_READ: 'entitlements.read',
  ENTITLEMENTS_MANAGE: 'entitlements.manage',
  BILLING_READ_OWN: 'billing.read_own',
  BILLING_MANAGE: 'billing.manage',
} as const;

export type PermissionString = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const SYSTEM_ROLES = {
  MAIN_ADMIN: 'MAIN_ADMIN',
  SUB_ADMIN: 'SUB_ADMIN',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
} as const;

export const ROLE_PERMISSIONS_MAP: Record<string, string[]> = {
  [SYSTEM_ROLES.MAIN_ADMIN]: Object.values(PERMISSIONS),
  [SYSTEM_ROLES.SUB_ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.QUESTIONS_READ,
    PERMISSIONS.QUESTIONS_CREATE,
    PERMISSIONS.QUESTIONS_UPDATE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_CREATE,
    PERMISSIONS.EXAMS_PUBLISH,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.RESULTS_READ_OWN,
    PERMISSIONS.RESULTS_FLAG,
    PERMISSIONS.ARCHIVE_READ,
    PERMISSIONS.ARCHIVE_ANSWER_KEY,
    PERMISSIONS.ARCHIVE_CORRECT,
    PERMISSIONS.ARCHIVE_EXPORT,
    PERMISSIONS.ANALYTICS_READ_OWN,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.PRACTICE_CREATE,
    PERMISSIONS.PRACTICE_READ,
    PERMISSIONS.PRACTICE_ATTEMPT,
    PERMISSIONS.PRACTICE_EVALUATE,
    PERMISSIONS.PREVIEW_USE,
    PERMISSIONS.PREVIEW_CONFIG,
    PERMISSIONS.IMPERSONATE_USE,
    PERMISSIONS.PREVIEW_AUDIT_READ,
    PERMISSIONS.AI_MODIFY,
    PERMISSIONS.AI_GENERATE,
    PERMISSIONS.AI_BATCH,
    PERMISSIONS.AI_REVIEW,
    PERMISSIONS.AI_USAGE_READ,
    PERMISSIONS.AI_ADMIN_CONFIG,
    PERMISSIONS.INTERVIEW_ATTEMPT,
    PERMISSIONS.INTERVIEW_READ_OWN,
    PERMISSIONS.INTERVIEW_MANAGE,
    PERMISSIONS.INTERVIEW_EVALUATE,
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.SUBSCRIPTIONS_MANAGE,
    PERMISSIONS.ENTITLEMENTS_READ,
    PERMISSIONS.ENTITLEMENTS_MANAGE,
    PERMISSIONS.BILLING_READ_OWN,
    PERMISSIONS.BILLING_MANAGE,
  ],
  [SYSTEM_ROLES.TEACHER]: [
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.QUESTIONS_READ,
    PERMISSIONS.QUESTIONS_CREATE,
    PERMISSIONS.QUESTIONS_UPDATE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_CREATE,
    PERMISSIONS.EXAMS_PUBLISH,
    PERMISSIONS.RESULTS_READ_OWN,
    PERMISSIONS.ARCHIVE_READ,
    PERMISSIONS.ARCHIVE_ANSWER_KEY,
    PERMISSIONS.ARCHIVE_EXPORT,
    PERMISSIONS.ANALYTICS_READ_OWN,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.PRACTICE_CREATE,
    PERMISSIONS.PRACTICE_READ,
    PERMISSIONS.PRACTICE_ATTEMPT,
    PERMISSIONS.PRACTICE_EVALUATE,
    PERMISSIONS.PREVIEW_USE,
    PERMISSIONS.PREVIEW_CONFIG,
    PERMISSIONS.AI_MODIFY,
    PERMISSIONS.AI_GENERATE,
    PERMISSIONS.AI_REVIEW,
    PERMISSIONS.AI_USAGE_READ,
    PERMISSIONS.INTERVIEW_ATTEMPT,
    PERMISSIONS.INTERVIEW_READ_OWN,
    PERMISSIONS.INTERVIEW_MANAGE,
    PERMISSIONS.INTERVIEW_EVALUATE,
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.ENTITLEMENTS_READ,
    PERMISSIONS.BILLING_READ_OWN,
  ],
  [SYSTEM_ROLES.STUDENT]: [
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_ATTEMPT,
    PERMISSIONS.RESULTS_READ_OWN,
    PERMISSIONS.RESULTS_FLAG,
    PERMISSIONS.ARCHIVE_READ,
    PERMISSIONS.ARCHIVE_EXPORT,
    PERMISSIONS.ANALYTICS_READ_OWN,
    PERMISSIONS.PRACTICE_CREATE,
    PERMISSIONS.PRACTICE_READ,
    PERMISSIONS.PRACTICE_ATTEMPT,
    PERMISSIONS.PRACTICE_EVALUATE,
    PERMISSIONS.AI_USAGE_READ,
    PERMISSIONS.INTERVIEW_ATTEMPT,
    PERMISSIONS.INTERVIEW_READ_OWN,
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.ENTITLEMENTS_READ,
    PERMISSIONS.BILLING_READ_OWN,
  ],
};

export function hasPermission(
  userPermissions: string[] | undefined,
  requiredPermission: string
): boolean {
  if (!userPermissions || !Array.isArray(userPermissions)) return false;
  return userPermissions.includes(requiredPermission) || userPermissions.includes('*');
}
